---
driver:
  name: vagrant
  gui: false
  customize:
    memory: 2048

provisioner:
  name: chef_zero
  attributes:
    appdynamics:
      version: '4.1.2.0'
      app_name: test-app
      tier_name: test-tier
      node_name: test-node
      controller:
        host: controller-host
        port: 443
        ssl: true
        user: controller-user
        accesskey: controller-accesskey
        http_proxy:
          host: http-proxy-host
          port: 2345
          user: http-proxy-user
          password_file: /tmp/foo/bar

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4
  - name: windows2012
    driver_config:
      box: opentable/win-2012r2-standard-amd64-nocm
      network:
        - ["forwarded_port", {guest: 3389, host: 33389}]
  - name: windows2008r2
    driver_config:
      box: opentable/win-2008r2-standard-amd64-nocm
      network:
        - ["forwarded_port", {guest: 3389, host: 33390}]

suites:
  - name: nodejs_agent
    run_list:
      - recipe[nodejs::default]
      - recipe[appdynamics::nodejs_agent]
    attributes:
      nodejs:
        install_method: source
      appdynamics:
        nodejs_agent:
          path: /home/vagrant
    excludes:
      - windows2012
      - windows2008r2

  - name: python_agent
    run_list:
      - recipe[python::default]
      - recipe[appdynamics::python_agent]
    attributes:
      appdynamics:
        python_agent:
          debug: true
          dir: '/opt/pyagent'
    excludes:
    - windows2012
    - windows2008r2

  - name: machine_agent
    run_list:
      - recipe[apt::default]
      - recipe[java::default]
      - recipe[appdynamics::machine_agent]
    excludes:
    - windows2012
    - windows2008r2

  - name: java_agent
    run_list:
      - recipe[test-helper::default]
      - recipe[appdynamics_test::java_agent]
      - recipe[apt::default]
      - recipe[appdynamics::java_agent]

    attributes:
      appdynamics:
        java_agent:
          owner: someuser
    excludes:
    - windows2012
    - windows2008r2

  - name: dotnet_agent
    run_list:
      - recipe[iis]
      - recipe[appdynamics::dotnet_agent]
    attributes:
      appdynamics:
        dotnet_agent:
          instrument_iis: true
          standalone_apps: [{name: W3SVC, executable: svchost.exe, tier: w3svc, commandline: -k iissvcs, restart: false },{name: MSDTC, executable: msdtc.exe, tier: msdtc, commandline: , restart: true}]
    chef_client:
      config:
        log_level: :debug
    excludes:
      - ubuntu-12.04
      - centos-6.4
