---
driver:
  name: vagrant
  customize:
    memory: 2048

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: nodejs_agent
    run_list:
      - recipe[nodejs::default]
      - recipe[appdynamics::nodejs_agent]
    attributes:
      nodejs:
        install_method: source
      appdynamics:
        app_name: test-app
        tier_name: test-tier
        node_name: test-node
        controller:
          host: controller-host
          port: 1234
          ssl: true
          user: controller-user
          accesskey: controller-accesskey
          http_proxy:
            host: http-proxy-host
            port: 2345
            user: http-proxy-user
            password_file: /tmp/foo/bar
        nodejs_agent:
          path: /home/vagrant
  - name: python_agent
    run_list:
      - recipe[python::default]
      - recipe[appdynamics::python_agent]
    attributes:
      appdynamics:
        app_name: test-app
        tier_name: test-tier
        node_name: test-node
        controller:
          host: controller-host
          port: 1234
          ssl: true
          user: controller-user
          accesskey: controller-accesskey
          http_proxy:
            host: http-proxy-host
            port: 2345
            user: http-proxy-user
            password_file: /tmp/foo/bar
          python_agent:
            debug: true
            dir: '/opt/pyagent'
  - name: machine_agent
    run_list:
      - recipe[apt::default]
      - recipe[java::default]
      - recipe[appdynamics::machine_agent]
    attributes:
      appdynamics:
        app_name: test-app
        tier_name: test-tier
        node_name: test-node
        controller:
          host: controller-host
          port: 1234
          ssl: true
          user: controller-user
          accesskey: controller-accesskey
          http_proxy:
            host: http-proxy-host
            port: 2345
            user: http-proxy-user
            password_file: /tmp/foo/bar
        machine_agent:
          source: http://10.0.72.177:10000/MachineAgent.zip
  - name: java_agent
    run_list:
      - recipe[apt::default]
      - recipe[appdynamics::java_agent]
    attributes:
      appdynamics:
        app_name: test-app
        tier_name: test-tier
        node_name: test-node
        controller:
          host: controller-host
          port: 1234
          ssl: true
          user: controller-user
          accesskey: controller-accesskey
        java_agent:
          source: http://10.0.72.177:10000/JavaAppAgent.zip
  - name: php_agent
    run_list:
      - recipe[apt::default]
      - recipe[php::default]
      - recipe[appdynamics::php_agent]
    attributes:
      appdynamics:
        app_name: test-app
        tier_name: test-tier
        node_name: test-node
        controller:
          host: controller-host
          port: 1234
          ssl: true
          user: controller-user
          accesskey: controller-accesskey
        php_agent:
          source: http://10.0.72.177:10000/appdynamics-php-agent.tar.bz2
