---
driver:
  name: vagrant
  gui: false
  customize:
    memory: 2048

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4
  - name: windows2012
    driver_config:
      box: opentable/win-2012r2-standard-amd64-nocm
      network:
        - ["forwarded_port", {guest: 3389, host: 33389}]
  - name: windows2008r2
    driver_config:
      box: opentable/win-2008r2-standard-amd64-nocm
      network:
        - ["forwarded_port", {guest: 3389, host: 33390}]

suites:
  - name: nodejs_agent
    run_list:
      - recipe[nodejs::default]
      - recipe[appdynamics::nodejs_agent]
    attributes:
      nodejs:
        install_method: source
      appdynamics:
        app_name: test-app
        tier_name: test-tier
        node_name: test-node
        controller:
          host: controller-host
          port: 1234
          ssl: true
          user: controller-user
          accesskey: controller-accesskey
          http_proxy:
            host: http-proxy-host
            port: 2345
            user: http-proxy-user
            password_file: /tmp/foo/bar
        nodejs_agent:
          path: /home/vagrant
    excludes:
      - windows2012
      - windows2008r2

  - name: python_agent
    run_list:
      - recipe[python::default]
      - recipe[appdynamics::python_agent]
    attributes:
      appdynamics:
        app_name: test-app
        tier_name: test-tier
        node_name: test-node
        controller:
          host: controller-host
          port: 1234
          ssl: true
          user: controller-user
          accesskey: controller-accesskey
          http_proxy:
            host: http-proxy-host
            port: 2345
            user: http-proxy-user
            password_file: /tmp/foo/bar
          python_agent:
            debug: true
            dir: '/opt/pyagent'
    excludes:
    - windows2012
    - windows2008r2

  - name: dotnet_agent
    run_list:
      - recipe[iis]
      - recipe[appdynamics::dotnet_agent]
    attributes:
      appdynamics:
        app_name: test-app
        controller:
          host: controller-host
          port: 443
          ssl: true
          user: controller-user
          accesskey: controller-accesskey
    chef_client:
      config:
        log_level: :debug
    excludes:
      - ubuntu-12.04
      - centos-6.4
