default['appdynamics']['dotnet_agent']['version'] = '4.0.7.0'
default['appdynamics']['dotnet_agent']['source'] = 'http://localhost/AppdynamicsInstallers/'
default['appdynamics']['dotnet_agent']['checksum'] = '1c73e49e0b24df53f048c814da992c2fdade5fc7c47aeb1aaccd4726d9a4d6f7'
default['appdynamics']['dotnet_agent']['install_dir'] = 'C:\Program Files\Appdynamics'
default['appdynamics']['dotnet_agent']['logfiles_dir'] = 'C:\DotNetAgent\Logs'
default['appdynamics']['dotnet_agent']['template']['cookbook'] = 'appdynamics'
default['appdynamics']['dotnet_agent']['template']['source'] = 'dotnet/setup.config.erb'
